### ISSUE TITLE
Will this work to deploy wordpress on docker

### ISSUE THREAD

**Issue by 9x3l6** [devbhusal/terraform-ec2-RDS-wordpress#2]
Will this work to deploy wordpress on Docker? I have a website https://fckr.cloud I want to use terraform to deploy the website on docker.

**Comment by devbhusal** [comment]
This should work on docker as well. Instead of editing wp-config file ,we can edt docket compose for wordpress

**Comment by 9x3l6** [comment]
Thank you!
